# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ uat ]
  pull_request:
    branches: [ uat ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 10.23.1
      uses: actions/setup-node@v1
      with:
        node-version: 10.23.1
    - run: npm run build --if-present
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.HOST_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.HOST }}
        # Remote user
        REMOTE_USER: ${{ secrets.HOST_USER }}
        SOURCE: build/
        TARGET: /opt/lode/website-2020
        
